authApp/urls.py
from django.urls import path
from . import views 
from . import ajax 

app_name = "auth"
urlpatterns = [
    path('', views.login),
    path('login/', views.login, name="login"),
    path('locked/', views.locked, name="locked"),
    path('disconnect/', views.disconnect, name="disconnect"),
    path('forgetpassword/', views.forgetpassword, name="forgetpassword"),
    path('reset/', views.reset, name="reset"),
    path('expiration/', views.expiration, name="expiration"),


    path('ajax/login/', ajax.connexion),
    path('ajax/first_user/', ajax.first_user),
    path('ajax/unlocked/', ajax.unlocked),
    path('ajax/forgetpassword/', ajax.forgetpassword),
    path('ajax/reset/', ajax.reset),

]

commandeApp/urls.py
from django.shortcuts import redirect
from django.urls import path
from django.urls.conf import include

from . import views
from . import ajax_new_commande

app_name = "commandes"
urlpatterns = [
    path('', views.commandes, name="commandes"),  
    path('commandes1/', views.commandes1, name="commandes1"),  
    path('prixparzone/', views.prixparzone, name="prixparzone"), 
    path('conversions/', views.conversions, name="conversions"),  


    path('ajax_new_commande/new_produit/', ajax_new_commande.new_produit, name="new_produit"), 
    path('ajax_new_commande/delete_ligne/', ajax_new_commande.delete_ligne, name="delete_ligne"), 
    path('ajax_new_commande/actualise/', ajax_new_commande.actualise, name="actualise"), 
    path('ajax_new_commande/total/', ajax_new_commande.total, name="total"), 
    path('ajax_new_commande/valider_commande/', ajax_new_commande.valider_commande, name="valider_commande"), 
    path('ajax_new_commande/changer_produit/', ajax_new_commande.changer_produit, name="changer_produit"), 
    path('ajax_new_commande/regler_commande/', ajax_new_commande.regler_commande, name="regler_commande"), 
]

ficheApp/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path
from django.urls.conf import include

from . import views, fiches

app_name = "fiches"
urlpatterns = [
    
    path('rapport_du_jour/<int:year>/<int:month>/<int:day>/', views.rapport_du_jour, name="rapport_du_jour"),



    path('prixparzone/<uuid:id>/', fiches.prixparzone, name="prixparzone"),
    path('commande/<uuid:id>/', fiches.commande, name="commande"),
    path('livraison/<uuid:id>/', fiches.livraison, name="livraison"),
    path('conversion/<uuid:id>/', fiches.conversion, name="conversion"),
    path('production/<uuid:id>/', fiches.production, name="production"),
    path('approvisionnement/<uuid:id>/', fiches.approvisionnement, name="approvisionnement"),
    path('achatstock/<uuid:id>/', fiches.achatstock, name="achatstock"),
    path('boncaisse/<uuid:id>/', fiches.boncaisse, name="boncaisse"),
]

settings/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

from organisationApp import views as orga

def home(request):
    if request.user.is_authenticated:
        return redirect("home/")
    return redirect("auth/login")

urlpatterns = i18n_patterns(
    path('', home),
    path('auth/', include('authApp.urls')),
    path('core/', include('coreApp.urls')),
    path('home/', include('organisationApp.urls')),

    path('boutique/', include('organisationApp.urls_boutique')),
    path('fabrique/', include('organisationApp.urls_fabrique')),
    path('manager/', include('organisationApp.urls_manager')),

    path('tresorerie/', include('comptabilityApp.urls')),

    path('fiches/', include('ficheApp.urls')),
    path('admin/', admin.site.urls),
    path('administration/', include('administrationApp.urls')),
    
)  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'authApp.views.handler404'
handler400 = 'authApp.views.handler400'
handler500 = 'authApp.views.handler500'

commandeApp/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
import datetime, uuid
from django.db.models import Sum, Avg

from coreApp.models import BaseModel, Etat
from productionApp.models import Brique
from livraisonApp.models import LigneLivraison
from comptabilityApp.models import ReglementCommande
# Create your models here.


class ZoneLivraison(BaseModel):
    name   = models.CharField(max_length = 255)
    agence = models.ForeignKey("organisationApp.Agence", on_delete = models.CASCADE, related_name="agence_zone")



class PrixZoneLivraison(BaseModel):
    zone   = models.ForeignKey(ZoneLivraison, on_delete = models.CASCADE, related_name="zone_prix") 
    brique = models.ForeignKey("productionApp.Brique", on_delete = models.CASCADE, related_name="brique_zoneprix") 
    price  = models.IntegerField(default=0)

    def __str__(self):
        return _("Prix de livraison de ")+self.brique.name+" à " +self.zone.name




class GroupeCommande(BaseModel):
    client = models.ForeignKey("clientApp.Client", on_delete = models.CASCADE, related_name="client_groupecommande")
    agence = models.ForeignKey("organisationApp.Agence", on_delete = models.CASCADE, related_name="agence_groupecommande")
    etat   = models.ForeignKey("coreApp.Etat", on_delete = models.CASCADE)
    datelivraison      = models.DateTimeField(null = True, blank=True,)

    def reste(self, brique):
        commades = LigneCommande.objects.filter(commande__groupecommande = self, commande__deleted = False, brique = brique).aggregate(Sum("quantite"))
        livraisons = LigneLivraison.objects.filter(livraison__groupecommande = self, brique = brique).exclude(livraison__etat__etiquette = Etat.ANNULE).aggregate(Sum("livree"))
        return (commades["quantite__sum"] or 0) - (livraisons["livree__sum"] or 0)

    def reste_a_payer(self):
        total = 0
        for commande in self.commande_groupecommande.filter(deleted = False):
            total += commande.reste_a_payer()
        return total
    
    
    def all_briques_all(self):
        briques = {}
        for brique in Brique.objects.filter(active = True, deleted = False):
            count =  self.reste(brique)
            briques[brique] = count
        return briques

    def all_briques(self):
        briques = {}
        for brique in Brique.objects.filter(active = True, deleted = False):
            count =  self.reste(brique)
            if count > 0:
                briques[brique] = count
        return briques

    def get_zones(self):
        tab = []
        for commande in self.commande_groupecommande.filter(deleted = False):
            if commande.zone not in tab : tab.append(commande.zone)
        return tab

    @staticmethod
    def maj_etat():
        try:
            groupes = GroupeCommande.objects.filter(etat__etiquette = Etat.EN_COURS, deleted = False)
            for groupe in groupes:
                if len(groupe.all_briques()) == 0:
                    groupe.etat = Etat.objects.get(etiquette = Etat.TERMINE)
                    groupe.save()
        except Exception as e:
            print("Erreur groupe commande ", e)
                


    def __str__(self):
        return _("Groupe de commande de ")+self.client.name




class Commande(BaseModel):
    groupecommande = models.ForeignKey(GroupeCommande, on_delete = models.CASCADE, related_name="commande_groupecommande")
    agence         = models.ForeignKey("organisationApp.Agence", on_delete = models.CASCADE, related_name="agence_commande")
    zone           = models.ForeignKey(ZoneLivraison, on_delete = models.CASCADE, related_name="zone_commande")
    lieu           = models.CharField(max_length = 255)
    montant        = models.FloatField(default = 0)
    avance         = models.FloatField(default = 0)
    taux_tva       = models.FloatField(default = 0)
    tva            = models.FloatField(default = 0)
    employe        = models.ForeignKey("organisationApp.Employe", on_delete = models.CASCADE, related_name="employe_commande")
    comment        = models.TextField(default="",  null = True, blank=True);
    is_conversion      = models.BooleanField(default = False)

    datelivraison  = models.DateField(null = True, blank=True,)
    acompte_client = models.FloatField(default = 0)
    dette_client   = models.FloatField(default = 0)
    class Meta:
        ordering = ['deleted', "-created_at"]

    def reste_a_payer(self):
        data = ReglementCommande.objects.filter(commande = self, deleted =False).aggregate(Sum("mouvement__montant"))
        return self.montant - (data["mouvement__montant__sum"] or 0)
    

    def all_briques(self):
        briques = {}
        for brique in Brique.objects.filter(active = True, deleted = False):
            ligne = LigneCommande.objects.filter(commande = self, commande__deleted = False, brique = brique).first()
            briques[brique] = ligne.quantite if ligne != None else 0
        return briques

    @staticmethod
    def chiffre_affaire(agence):
        total = Commande.objects.filter(deleted = False, agence = agence).aggregate(Sum("montant"))
        return total["montant__sum"] or 0


    def __str__(self):
        return _("Commande N°")+str(self.id)



class LigneCommande(BaseModel):
    commande = models.ForeignKey(Commande, on_delete = models.CASCADE, related_name="commande_ligne")
    brique   = models.ForeignKey("productionApp.Brique", on_delete = models.CASCADE, related_name="brique_lignecommande")
    quantite = models.IntegerField(default = 0)
    price    = models.IntegerField(default = 0)


    def __str__(self):
        return str(self.quantite) + " " +self.brique.name+" à " +str(self.price)




class Conversion(BaseModel):
    agence             = models.ForeignKey("organisationApp.Agence", on_delete = models.CASCADE, related_name="agence_conversion")
    groupecommande_old = models.ForeignKey(GroupeCommande, on_delete = models.CASCADE, related_name="old_groupecommande_conversion")
    groupecommande_new = models.ForeignKey(GroupeCommande, on_delete = models.CASCADE, related_name="new_groupecommande_conversion")
    employe        = models.ForeignKey("organisationApp.Employe",  null = True, blank=True, on_delete = models.CASCADE, related_name="employe_transfertstock")

    def __str__(self):
        return _("Conversion N°")+str(self.id)

class LigneConversion(BaseModel):
    conversion      = models.ForeignKey(Conversion, on_delete = models.CASCADE, related_name="conversion_ligne")
    brique         = models.ForeignKey(Brique, on_delete = models.CASCADE, related_name="brique_conversionligne")
    quantite_avant = models.IntegerField(default=0)
    quantite_apres = models.IntegerField(default=0)

    def __str__(self):
        return str(self.quantite_avant) + " " +self.brique.name+" => " +str(self.quantite_apres)


######################################################################################################
##### SIGNAUX



@receiver(post_save, sender = ZoneLivraison)
def post_save_zone_livraison(sender, instance, created, **kwargs):
    if created:
        for brique in Brique.objects.filter(deleted = False):
            PrixZoneLivraison.objects.create(
                brique = brique,
                zone = instance,
                price = 0
            )



@receiver(pre_save, sender = GroupeCommande)
def pre_save_groupe_commande(sender, instance, **kwargs):
    if instance._state.adding:
        instance.datelivraison = datetime.datetime.now()
        instance.etat = Etat.objects.get(etiquette = Etat.EN_COURS)



@receiver(pre_save, sender = Commande)
def pre_save_commande(sender, instance, **kwargs):
    if instance._state.adding:
        if instance.datelivraison is None:
            raise Exception("Veuillez notifier une date correcte de livraison pour la commande")
        if instance.lieu == "":
            raise Exception("Veuillez préciser le lieu exact de la livraison !")
        instance.etat = Etat.objects.get(etiquette = Etat.EN_COURS)



@receiver(post_save, sender = Commande)
def post_save_commande(sender, instance, created, **kwargs):
    pass
    # date =  instance.groupecommande.datelivraison.replace(tzinfo=None)
    # if date < datetime.datetime.now():
    #     if instance.groupecommande.datelivraison is None or instance.groupecommande.datelivraison < instance.datelivraison:
    #         instance.groupecommande.datelivraison = instance.datelivraison
    #         instance.groupecommande.save()

commandeApp/forms.py
from .models import *
from django.forms import ModelForm
# Create your models here.


class GroupeCommandeForm(ModelForm):
    class Meta:
        fields = "__all__"
        model = GroupeCommande


class CommandeForm(ModelForm):
    class Meta:
        fields = "__all__"
        model = Commande


class LigneCommandeForm(ModelForm):
    class Meta:
        fields = "__all__"
        model = LigneCommande



class ZoneLivraisonForm(ModelForm):
    class Meta:
        fields = "__all__"
        model = ZoneLivraison



class PrixZoneLivraisonForm(ModelForm):
    class Meta:
        fields = "__all__"
        model = PrixZoneLivraison

commandeApp/views.py
from django.shortcuts import render
from comptabilityApp.models import ModePayement
from livraisonApp.models import Chauffeur, ModeLivraison, Vehicule
from productionApp.models import Brique
from commandeApp.models import Conversion, ZoneLivraison, PrixZoneLivraison
from commandeApp.models import GroupeCommande
from coreApp.models import Etat
import datetime
# Create your views here.


def commandes(request):
    if request.method == "GET":
        GroupeCommande.maj_etat()
        datas = []
        for groupe in GroupeCommande.objects.filter(etat__etiquette = Etat.EN_COURS):

            commandes = groupe.commande_groupecommande.filter(deleted = False)
            livraisons = groupe.groupecommande_livraison.filter(deleted = False).exclude(etat__etiquette = Etat.ANNULE)

            for commande in commandes:
                commande.tipe = "commande"
            for livraison in livraisons:
                livraison.tipe = "livraison"

            mylist = [] 
            mylist.extend(commandes)
            mylist.extend(livraisons)
            mylist.sort(key=lambda x: x.created_at)
            datas.append({
                "groupe":groupe,
                "commandes": commandes,
                "livraisons": livraisons,
                "livraisons_encours": groupe.groupecommande_livraison.filter(deleted = False, etat__etiquette = Etat.EN_COURS),
                "sort_lignes": mylist,
                "briques" : groupe.all_briques()
            })
            
        context = {
            "datas" : datas,
            "briques" : Brique.objects.filter(active = True, deleted = False),
            'commandes' : GroupeCommande.objects.filter(etat__etiquette = Etat.EN_COURS, deleted = False),
            "chauffeurs": Chauffeur.objects.filter(deleted = False, agence = request.agence),
            "vehicules": Vehicule.objects.filter(deleted = False, agence = request.agence),
            "modepayements": ModePayement.objects.filter(deleted = False),
            "zonelivraisons": ZoneLivraison.objects.filter(deleted = False, agence = request.agence),
            "modelivraisons": ModeLivraison.objects.filter(deleted = False),
        }
        return render(request, "commande/pages/commandes.html", context)




def commandes1(request):
    context = {}
    return render(request, "commande/pages/commandes1.html", context)



def conversions(request):
    debut = datetime.date.fromisoformat(request.session["date1"])
    fin = datetime.date.fromisoformat(request.session["date2"])
    lendemain = fin + datetime.timedelta(days= 1)

    context = {
        "conversions" : Conversion.objects.filter(deleted= False, created_at__range=(debut, lendemain))
    }
    return render(request, "commande/pages/conversions.html", context)




def prixparzone(request):
    if request.method == "GET":
        context = {
            "briques" : Brique.objects.filter(active = True),
            "zones" : ZoneLivraison.objects.filter(agence = request.agence),
            "prixparzones" : PrixZoneLivraison.objects.filter(zone__agence = request.agence)
        }
        return render(request, "commande/pages/prixparzone.html", context)

commandeApp/templates/commande/modals/changer_produit.html
{% load static %} 
{% load i18n %}
{% load myfilters %}
<div class="modal inmodal fade" id="modal-changement-{{item.groupe.id}}" style="z-index: 99999999">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">{% translate "Nouveau interchangement de produit" %}</h4>
            <small class="font-bold">{% translate "Renseigner ces champs pour enregistrer le changement" %}</small>
        </div>
        
        <div class="row">
            <div class="col-md-8">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5 class="text-uppercase">{% translate "Définissez le changement de briques" %}</h5>
                    </div>
                    <div class="ibox-content"><br>
                        <div class="table-responsive">
                            <table class="table  table-striped">
                                <thead>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td class="text-center">{% translate "Qté actuelle" %}</td>
                                        <td></td>
                                        <td>{% translate "Nouvelle Qté" %}</td>
                                    </tr>
                                </thead>
                                <tbody class="commande">
                                    {% for brique in briques %}
                                        <tr class="border-0 border-bottom" data-id="{{ brique.id }}">
                                            <td >
                                                <img style="width: 40px" src="{% static brique.image %}">
                                            </td>
                                            <td class="text-left">
                                                <h4 class="mp0 text-uppercase">{{ brique.name }}</h4>
                                                <small>{{ brique.comment }}</small>
                                            </td>
                                            <td><h3 class="gras text-center">{{item.briques|dict_value:brique | start0 }}</h3></td>
                                            <td><h3 class="gras">=></h3></td>
                                            <td width="105"><input type="number" number class="form-control text-center gras" value="{{item.briques|dict_value:brique}}" max="{{item.briques|dict_value:brique}}"></td>
                                        </tr>
                                    {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 ">
            <div class="ibox"  style="background-color: #eee">
                <div class="ibox-title" style="padding-right: 2%; padding-left: 3%; ">
                    <h5 class="text-uppercase">{% translate "Finaliser le changement" %}</h5>
                </div>
                <div class="ibox-content"  style="background-color: #fafafa">
                    <form class="formChangement">
                        <div>
                            <label>{% translate "Motif du changement" %} </label>
                            <textarea class="form-control" rows="4" name="comment"></textarea>
                        </div><br>
                        <hr/>
                        <button type="submit" class="btn btn-default btn-block dim"><i class="fa fa-check"></i> {% translate "Valider le changement" %}</button>
                    </form>
                </div>
            </div>

        </div>
    </div>

</div>
</div>
</div>

commandeApp/templates/commande/modals/commande_infos.html
{% load static %} 
{% load i18n %}
{% load humanize %}
{% load myfilters %}

<div class="modal inmodal fade" id="infos-groupecommande-{{ item.groupe.id }}">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-body">
                <div class="ibox-content">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <div class="row">
                        <div class="col-sm-5">
                          <div class="row">
                            <div class="col-3">
                                <img style="height: 100px" src="{% static request.societe.image %}">
                            </div>
                            <div class="col-9">
                                <h5 class="gras text-uppercase text-orange">{{ request.societe.name }}</h5>
                                <h5 class="mp0">{{ request.societe.postale }}</h5>
                                <h5 class="mp0">{% translate "Tél" %}: {{ request.societe.contact }}</h5>
                                <h5 class="mp0">{% translate "Email" %}: {{ request.societe.email }}</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-7 text-right">
                      <h2 class="title text-uppercase gras">{% translate "Fiche de commande" %}</h2>
                      <h3 class="text-uppercase">{{ item.groupe.client.name}} // <span style="font-weight: normal;"><{{ item.groupe.client.type.name}}</span></h3>
                        <h5>{{ item.groupe.client.contact}} // {{ item.groupe.client.email }}</h5>
                    </div>
                </div><hr>

                <div class="scroll" style="overflow-x: scroll;">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th colspan="3"></th>
                                {% for brique in item.briques %}
                                <th class="text-center" style="padding: 2px">
                                    <img style="height: 20px" >
                                    <span class="small">{{ brique.name }}</span>
                                </th>
                                {% endfor %}
                                <th style="width: 150px" class="text-center">{% translate "RESTE A PAYER" %}</th>
                                <th class="text-center">{% translate "OPTIONS" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for element in item.sort_lignes %}
                            {% if element.tipe == "commande" %}
                            <tr>
                              <td data-toggle="tooltip" title="{% translate 'Supprimer la commande' %}">
                                <i class="fa fa-trash fa-2x d-block text-red cursor" onclick="delete_password('commande', '{{ element.id }}')"></i> 
                            </td>
                            <td>
                                <h5 class="text-uppercase mp0">{% translate "Commande N°" %}{{element.id}}</h5>
                                <small>{{element.created_at | naturaltime }}</small>
                            </td>
                            <td data-toggle="tooltip" title="{% translate 'imprimer le bon de commande' %}">
                                <a target="_blank" href="{% url 'fiches:commande' element.id %}">
                                    <i class="d-block fa fa-file-text fa-2x text-orange"></i>
                                </a>                               
                            </td>
    
                            {% for brique in item.briques %}
                            <td>
                                <h3 class="text-orange text-center"> {{ element.all_briques|dict_value:brique | start0 }}</h3>
                            </td>
                            {% endfor %}
    
                            <td class="text-center">
                                <h3 class="text-danger">{{ element.reste_a_payer| intcomma }} {{ request.societe.devise }} </h3>
                            </td>
                            <td class="text-center">
                                <button class="btn btn-info btn-xs dim" title="Voir la liste des versements pour cette commande" data-toggle="modal" data-target="#modal-versements-commande-{{ element.id }}"><i class="fa fa-list"></i> </button>
                                {% if element.reste_a_payer > 0 %}
                                <button class="btn btn-danger btn-xs dim" data-toggle="modal" data-target="#modal-regler-commande-{{ element.id }}"><i class="fa fa-money"></i> {% translate "Regler le reste" %}</button>
                                {% endif %}
                            </td>
                        </tr>
                        
                        {% else %}
                        
                        <tr>
                            <td data-toggle="tooltip" >
                                {% if element.etat.etiquette|add:0 == request.etat.EN_COURS|add:0 %}
                                <i title="Annuler la livraison" class="fa fa-close fa-2x d-block text-red cursor" onclick="delete_password('livraison', '{{ element.id }}')"></i> 
                                {% endif %}
                            </td>
                            <td>
                              <h5 class="text-uppercase mp0">{% translate "Livraison N°" %}{{element.id}}</h5>
                              <small>{{element.created_at | naturaltime }}</small>
                            </td>
                          <td data-toggle="tooltip" title="{% translate 'imprimer le bon de livraison' %}">
                              <a target="_blank" href="{% url 'fiches:livraison' element.id %}">
                                  <i class="d-block fa fa-file-text fa-2x text-green"></i>
                                </a>                               
                            </td>
                            
                            {% for brique in item.briques %}
                            <td>
                                <h3 class="text-green text-center"> {{ element.all_briques|dict_value:brique | start0 }}</h3>
                            </td>
                            {% endfor %}
  
                          <td class="text-center">
                              <h3 class="text-danger"></h3>
                          </td>
                          <td class="text-center">
                              
                          </td>
                      </tr>

                        {% endif %}

                        {% endfor %}
    
                        <tr style="height: 20px;"></tr>
    
                        <tr>
                            <td colspan="3"><h2 class="text-uppercase text-right">{% translate "Reste à livrer" %} : </h2></td>
                            {% for brique in item.briques %}
                            <td widtd="90" class="text-center">
                                    <h2 class="gras">{{ item.briques|dict_value:brique | start0 }}</h2>
                                </td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
                </div><br><hr>

            <div class="row text-center" style="font-size: 12px">
                {% if item.groupe.etat.etiquette|add:"0" == request.etat.EN_COURS|add:"0" %}
                    <div class="col-md">
                        <button class="btn btn-primary dim" data-toggle=modal data-target='#modal-newcommande'><i class="fa fa-cart-plus"></i> {% translate "Nouvelle commande" %}</button>
                    </div>
                    <div class="col-md">
                        <button class="btn btn-default dim" data-toggle="modal" data-target='#modal-changement-{{item.groupe.id}}'><i class="fa fa-refresh"></i> {% translate "Changement de produits" %} </button>
                    </div>
                    <div class="col-md">
                        <button class="btn btn-warning dim" data-toggle="modal" data-target='#modal-livraison-{{item.groupe.id}}'><i class="fa fa-truck"></i> {% translate "Faire livraison aujourd'hui" %}</button>
                    </div>
                {% endif %}
            </div>
        </div>

    </div>
</div>
</div>
</div>

commandeApp/templates/commande/modals/liste_versement.html
{% load humanize %}

{% load i18n %} 
<div class="modal inmodal fade" id="modal-versements-commande-{{ commande.id }}">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">{% translate "Versements pour la commande" %}</h4>
            </div>
            <div class="modal-body">
                {% if reglements|length > 0 %}
                    {% for reglement in reglements %}
                    <a href="{% url 'fiches:boncaisse' reglement.mouvement.id %}" class="text-dark">
                        <div class="contact-box mp5">
                            <div class="row">
                                <div class="col-sm-7">
                                    <h4>{{ reglement.mouvement.created_at | date:"d F Y à H:i:s" }}</h4>
                                    <h5 class="text-muted">{% translate "Payement par" %} {{ reglement.mouvement.mode.name }}</h5>
                                </div>
                                <div class="col-sm-5 text-right">
                                    <h3>{{ reglement.mouvement.montant | intcomma }} {{request.societe.devise }}</h3>
                                    <h5 class="text-danger">{% translate "Restait à payer" %} : {{ reglement.restait | intcomma }} {{request.societe.devise }}</h5>
                                </div>
                            </div>
                        </div>
                    </a>

                    <div class="text-center div-divider">
                        <p class="mp0 divider"></p>
                    </div>
                    {% endfor %}
                {% else %}
                {% include 'extra/empty.html' %}
                {% endif %}
            </div>
        </div>
    </div>
</div>



<style>
    .divider {
        height:30px;
        width: 3px;
        background-color: grey; 
        display:inline-block;
    }
    .div-divider:last-child {
        display: none; 
    }
</style>